---
swagger: "2.0"
info:
  version: "1.0"
  title: "sprintpss"
basePath: "/Stage"
schemes:
- "https"
paths:
  /serverdate:
    get:
      responses: {}
      security:
      - basic-authorizer: []
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:749574521452:function:local-date-svc:live/invocations"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        type: "aws_proxy"
